services:
  ubuntu-1804:
    command: ./build.sh
    environment:
      - R_VERSION=${R_VERSION}
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: Dockerfile.ubuntu-1804
    image: r-builds:ubuntu-1804
    volumes:
      - ./integration/tmp:/tmp/output
  ubuntu-2004:
    command: ./build.sh
    environment:
      - R_VERSION=${R_VERSION}
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: Dockerfile.ubuntu-2004
    image: r-builds:ubuntu-2004
    volumes:
      - ./integration/tmp:/tmp/output
  ubuntu-2204:
    command: ./build.sh
    environment:
      - R_VERSION=${R_VERSION}
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: Dockerfile.ubuntu-2204
    image: r-builds:ubuntu-2204
    volumes:
      - ./integration/tmp:/tmp/output
  debian-10:
    command: ./build.sh
    environment:
      - R_VERSION=${R_VERSION}
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: Dockerfile.debian-10
    image: r-builds:debian-10
    volumes:
      - ./integration/tmp:/tmp/output
  debian-11:
    command: ./build.sh
    environment:
      - R_VERSION=${R_VERSION}
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: Dockerfile.debian-11
    image: r-builds:debian-11
    volumes:
      - ./integration/tmp:/tmp/output
  centos-7:
    command: ./build.sh
    environment:
      - R_VERSION=${R_VERSION}
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: Dockerfile.centos-7
    image: r-builds:centos-7
    volumes:
      - ./integration/tmp:/tmp/output
  centos-8:
    command: ./build.sh
    environment:
      - R_VERSION=${R_VERSION}
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: Dockerfile.centos-8
    image: r-builds:centos-8
    volumes:
      - ./integration/tmp:/tmp/output
  rhel-9:
    command: ./build.sh
    environment:
      - R_VERSION=${R_VERSION}
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: Dockerfile.rhel-9
    image: r-builds:rhel-9
    volumes:
      - ./integration/tmp:/tmp/output
  opensuse-153:
    command: ./build.sh
    environment:
      - R_VERSION=${R_VERSION}
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: Dockerfile.opensuse-153
    image: r-builds:opensuse-153
    volumes:
      - ./integration/tmp:/tmp/output
  opensuse-154:
    command: ./build.sh
    environment:
      - R_VERSION=${R_VERSION}
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: Dockerfile.opensuse-154
    image: r-builds:opensuse-154
    volumes:
      - ./integration/tmp:/tmp/output
